uploadsapp/homework/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static

from homework import views

urlpatterns = patterns('',

 url(r'^$', views.accueil, name='accueil'),
 url(r'^inscription/', views.inscription, name='inscription'),
 url(r'^connexion/', views.connexion, name='connexion'),
 url(r'^deconnexion/', views.deconnexion, name='deconnexion'),
 url(r'^bureau/', views.bureau, name='bureau'),
 url(r'^classes/', views.classeIndex, name='classeIndex'),
 url(r'^classe/(?P<classeNom>\w+)/', views.classeEdition, name='classeEdition'),
 url(r'^devoirs/', views.devoirIndex, name='devoirIndex'),
 url(r'^devoir/(?P<devoirTitre>\w+)/', views.devoirEdition, name='devoirEdition'),
 url(r'^chargerimage/(?P<devoirTitre>\w+)/', views.chargerImage, name='chargerImage'),
 url(r'^mesImages/', views.imageIndexEtudiant, name='imageIndexEtudiant'),
 url(r'^monimage/(?P<devoirTitre>\w+)/', views.imageEditionEtudiant, name='imageEditionEtudiant'),
 url(r'^images/(?P<devoirTitre>\w+)/', views.imageIndexProfesseur, name='imageIndexProfesseur'),
 url(r'^image/(?P<imageId>\w+)/', views.imageEditionProfesseur, name='imageEditionProfesseur')
 
)

uploadsapp/uploadsapp/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^homework/', include('homework.urls', namespace="homework")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploadsapp/homework/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Etudiant(models.Model):
    user = models.OneToOneField(User)
    classe = models.ManyToManyField('Classe')
    
    def __str__(self):
        return "Etudiant {}".format(self.user.username)

class Professeur(models.Model):
    user = models.OneToOneField(User) 
    
    def __str__(self):
        return "Professeur {}".format(self.user.username)
        
class Classe(models.Model):
    nom = models.CharField(max_length=50)
    branche = models.CharField(max_length=50)
    professeur = models.ForeignKey("Professeur")
    
    def __str__(self):
        return "{}: {}".format(self.branche, self.nom)
        
class Image(models.Model):
    etudiant = models.ForeignKey("Etudiant")
    photo = models.ImageField(upload_to="etudiants/images")
    devoir = models.ForeignKey("Devoir")
    
    description = models.CharField(max_length=300, null=True)
    
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return "{}: {}".format(self.devoir, self.etudiant)
        
class Devoir(models.Model):
    professeur = models.ForeignKey("Professeur")
    classe = models.ManyToManyField("Classe")
    
    titre = models.CharField(max_length=50)
    consigne = models.CharField(max_length=300)
    consigneImg = models.ImageField(upload_to="professeur/consignes", null=True)
    reponse = models.CharField(max_length=300, null=True)
    reponseImg = models.ImageField(upload_to="professeur/corriges", null=True)
    
    dateCreation = models.DateField(auto_now_add=True)
    dateReddition = models.DateField()
    
    def __str__(self):
        return self.titre

uploadsapp/homework/forms.py
from django import forms
from django.forms.extras.widgets import *

from homework.models import Classe, Etudiant

class InscriptionForm(forms.Form):
    prenom = forms.CharField(label="Prénom", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    nom = forms.CharField(label="Nom", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    courriel = forms.CharField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'validate', 'type': 'email'}))
    modeleCompte = forms.ChoiceField(label='Type de compte', choices=(
        ("professeur", "Professeur"),
        ("etudiant", "Étudiant"),
        ))
    pseudo = forms.CharField(label="Pseudo", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    motDePasse = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class': 'validate', 'type': 'password'}))

class ConnexionForm(forms.Form):
    pseudo = forms.CharField(label="Pseudo", max_length=30, widget=forms.TextInput())
    motDePasse = forms.CharField(label="Mot de passe", widget=forms.PasswordInput())
    
class CreerClasseForm(forms.Form):
    nom = forms.CharField(label="Nom", max_length=50, widget=forms.TextInput())
    branche = forms.ChoiceField(label='Branche', choices=(
        ("", "Choisissez votre Branche"),
        ("Allemand", "Allemand"),
        ("Anglais", "Anglais"),
        ("Arts Visuels", "Arts Visuels"),
        ("Biologie", "Biologie"),
        ("Chimie", "Chimie"),
        ("Français", "Français"),
        ("Histoire", "Histoire"),
        ("Maths", "Maths"),
        ("Musique", "Musique"),
        ("Philosophie", "Philosophie"),
        ("Physique", "Physique"),
        ("Sport", "Sport"),
        ))
    
class EtudiantAjoutForm(forms.Form):
    etudiants = forms.ModelMultipleChoiceField(label="Etudiants à ajouter", queryset=Etudiant.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())

class EtudiantSupprForm(forms.Form):
    etudiants = forms.ModelMultipleChoiceField(label="Etudiants à supprimer", queryset=Etudiant.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())

class QuitterClasseForm(forms.Form):
    nomClasse = forms.CharField(label="Saisir le nom de la classe pour quitter", max_length=50, widget=forms.TextInput())
    
class CreerDevoirForm(forms.Form):
    titre = forms.CharField(label="Titre", max_length=50, widget=forms.TextInput())
    consigne = forms.CharField(label="Consigne", max_length=300, widget=forms.Textarea())
    consigneImg = forms.ImageField(label="Consigne en image", widget=forms.FileInput(attrs={'accept': 'image/*'}))
    reponse = forms.CharField(label="Réponse",  max_length=300, widget=forms.Textarea())
    reponseImg = forms.ImageField(label="Réponse en image", widget=forms.FileInput(attrs={'accept': 'image/*'}))
    dateReddition = forms.DateField(label="Date de reddition", widget=forms.DateInput())
    classe = forms.ModelMultipleChoiceField(label="Classes", queryset=Classe.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())
    
class DevoirConsForm(forms.Form):
    consigne = forms.CharField(label="Consigne", max_length=300, widget=forms.Textarea())
    
class DevoirConsImgForm(forms.Form):
    consigneImg = forms.ImageField(label="Consigne en image", widget=forms.FileInput())

class DevoirRepForm(forms.Form):
    reponse = forms.CharField(label="Réponse", max_length=300, widget=forms.Textarea())

class DevoirRepImgForm(forms.Form):
    reponseImg = forms.ImageField(label="Réponse en image", widget=forms.FileInput())

class DevoirDateForm(forms.Form):
    dateReddition = forms.DateField(label="Date de reddition", widget=forms.DateInput())

class ChargerImageForm(forms.Form):
    photo = forms.ImageField(label="Photo")
    description = forms.CharField(label="Description", required=False, max_length=300, widget=forms.Textarea(attrs={'class': 'validate', 'type': 'text'}))

uploadsapp/homework/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group

from homework.auth_utils import *
from homework.models import *
from homework.forms import *

def accueil(request):
    return render(request, "homework/accueil.html")
    
def inscription(request):
    if request.user.is_authenticated():
        return redirect("homework:bureau")
    else:
        if request.method == "POST":
            inscriptionForm = InscriptionForm(request.POST, request.FILES)
            
            if inscriptionForm.is_valid():
                username = inscriptionForm.cleaned_data["pseudo"]
                password = inscriptionForm.cleaned_data["motDePasse"]
                first_name = inscriptionForm.cleaned_data["prenom"]
                last_name = inscriptionForm.cleaned_data["nom"]
                eMail = inscriptionForm.cleaned_data["courriel"]
                
                try:
                    User.objects.get(username=username)
                
                except User.DoesNotExist:
                    modeleCompte = None
                    
                    if inscriptionForm.cleaned_data["modeleCompte"] == "etudiant":
                        modeleCompte = Etudiant()
                        group_name = "étudiants"
                        
                    elif inscriptionForm.cleaned_data["modeleCompte"] == "professeur":
                        modeleCompte = Professeur()
                        group_name = "professeurs"
                        
                    user = User.objects.create_user(username, eMail, password)
                    user.first_name = first_name
                    user.last_name = last_name
                    
                    try:
                        groupe = Group.objects.get(name=group_name)
                    
                    except:
                        groupe = Group.objects.create(name=group_name)
                    
                    user.groups.add(groupe)
                    user.save()
                        
                    compte = modeleCompte
                    compte.user = user
                    compte.save()
                    
                    return redirect("homework:connexion")
    
        else:
            inscriptionForm = InscriptionForm()
            
        return render(request, "homework/inscription.html", locals())

def connexion(request):
    if request.user.is_authenticated():
        return redirect("homework:bureau")
    else:    
        erreur = False
        
        if request.method == "POST":
            connexionForm = ConnexionForm(request.POST, request.FILES)
            
            if connexionForm.is_valid():
                username = connexionForm.cleaned_data["pseudo"]
                password = connexionForm.cleaned_data["motDePasse"]
                user = authenticate(username=username, password=password)
                
                if user:
                    login(request, user)
                    
                    return redirect("homework:bureau")
                else:
                    erreur = True
        else:
            connexionForm = ConnexionForm()
            
        return render(request, "homework/connexion.html", locals())
        #return render(request, "material/connexion.html", locals())
        
def deconnexion(request):
    logout(request)
    
    return redirect("homework:accueil")
    
def bureau(request):
    if estEtudiant(request.user):
        etudiant = Etudiant.objects.get(user=request.user)
        classes = etudiant.classe.all()
        images = Image.objects.filter(etudiant=etudiant)
        
        devoirs = Devoir.objects.all().filter(classe=classes).distinct().order_by("-dateReddition")
        
        dejaFait = []
        devoirsAFaire = []
        
        for devoir in devoirs:
            for image in images:
                if image.devoir == devoir:
                    dejaFait.append(devoir)
        
        for devoir in devoirs:
            if devoir not in dejaFait:
                devoirsAFaire.append(devoir)
                
        return render(request, "etudiant/bureau.html", locals())
    
    elif estProfesseur(request.user):
        professeur = Professeur.objects.get(user=request.user)
        classes = Classe.objects.filter(professeur=professeur)
        eleves = []
        
        for classe in classes:
            elevesAAjouter = Etudiant.objects.filter(classe=classe)
            for eleveAAjouter in elevesAAjouter:
                eleves.append(eleveAAjouter)
        
        images = Image.objects.all().order_by("-date")
        
        imagesAMontrer = []
        
        while len(imagesAMontrer) < 5:
            for image in images:
                if image.etudiant in eleves and image not in imagesAMontrer:
                    imagesAMontrer.append(image)
            if len(images) == len(imagesAMontrer):
                break
        if len(imagesAMontrer) == 0:
            imageAucune = True
        else:
            imageAucune = False
        return render(request, "professeur/bureau.html", locals())
    
    else:
        return redirect("homework:connexion")

def classeIndex(request):
    if estProfesseur(request.user):
        erreur = False
        professeur = Professeur.objects.get(user=request.user)
        classes = Classe.objects.filter(professeur=professeur)
        
        if request.method == "POST":
            creerClasseForm = CreerClasseForm(request.POST, request.FILES)
            if creerClasseForm.is_valid():
                classeNom = creerClasseForm.cleaned_data["nom"]
                try:
                    classe = Classe.objects.get(nom=classeNom)
                    erreur = True
                except:
                    classe = Classe()
                    classe.nom = classeNom
                    classe.branche = creerClasseForm.cleaned_data["branche"]
                    classe.professeur = professeur
                    classe.save()
                    creerClasseForm = CreerClasseForm()
        else:
            creerClasseForm = CreerClasseForm()
        
        branches = [("Allemand"),
                    ("Anglais"),
                    ("Arts Visuels"),
                    ("Biologie"),
                    ("Chimie"),
                    ("Français"),
                    ("Histoire"),
                    ("Maths"),
                    ("Musique"),
                    ("Philosophie"),
                    ("Physique"),
                    ("Sport")]
                    
        return render(request, "professeur/classeIndex.html", locals())
    
    elif estEtudiant(request.user):
        etudiant = Etudiant.objects.get(user=request.user)
        classes = etudiant.classe.all()
        
        return render(request, "etudiant/classeIndex.html", locals())
        
    else:
        return redirect("homework:connexion")

def classeEdition(request, classeNom):
    if estProfesseur(request.user) or estEtudiant(request.user):
        classe = Classe.objects.get(nom=classeNom)
        classeEtudiants = Etudiant.objects.filter(classe=classe)
        classeProfesseur = classe.professeur
        etudiantsTous = Etudiant.objects.exclude(classe=classe)
        
        if estProfesseur(request.user):
            professeurConnecte = Professeur.objects.get(user=request.user)
            if professeurConnecte == classeProfesseur:
                if request.method == "POST":
                    if 'etudiantSuppr' in request.POST:
                        etudiantSupprForm = EtudiantSupprForm(request.POST, request.FILES)              
                        if etudiantSupprForm.is_valid():                                                
                            for etudiant in etudiantSupprForm.cleaned_data["etudiants"]:                
                                etudiant.classe.remove(classe)                             
                                etudiant.save()
                                
                                etudiantSupprForm = EtudiantSupprForm()
                                etudiantAjoutForm = EtudiantAjoutForm()
                                etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                                etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
        
                    elif 'etudiantAjout' in request.POST:
                        etudiantAjoutForm = EtudiantAjoutForm(request.POST, request.FILES)
                        if etudiantAjoutForm.is_valid():
                            for etudiant in etudiantAjoutForm.cleaned_data["etudiants"]:
                                etudiant.classe.add(classe)
                                etudiant.save()
                                
                                etudiantSupprForm = EtudiantSupprForm()
                                etudiantAjoutForm = EtudiantAjoutForm()
                                etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                                etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
                else:
                    etudiantSupprForm = EtudiantSupprForm()
                    etudiantAjoutForm = EtudiantAjoutForm()
                    etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                    etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
                
                return render(request, "professeur/classeEditionPropre.html", locals())
            else:
                return render(request, "professeur/classeEditionAutre.html", locals())
        
        elif estEtudiant(request.user):

uploadsapp/homework/templates/etudiant/bureau.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    Bureau
{% endblock %}

{% block logo %}
    Bureau
{% endblock %}

{% block body %}
    {% for devoir in devoirsAFaire %}
    <div class="row">
        <div class="col s12">
          <div class="card">
            <div class="card-image">
              <img src="{{ devoir.consigneImg.url }}">
              <span class="card-title">{{ devoir.titre}}</span>
            </div>
            <div class="card-content">
              <p>{{ devoir.consigne }}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'homework:chargerImage' devoir.titre %}">Résoudre !</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
{% endblock %}

uploadsapp/homework/templates/etudiant/chargerImage.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    {{ devoir }}
{% endblock %}

{% block logo %}
{{ devoir.titre }}
{% endblock %}

{% block body %}
    {% if dejaFait %}
    <div class="row">
        <div class="col s12 ">
            <div class="card">
                <div class="card-content">
                    <span class="card-title  black-text">Attention</span>
                    <p>Vous avez déjà fait ce devoir.</div>
                    <div class="card-action">
                    <a href="{% url 'homework:bureau'%}">Bureau</a>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col s12">
          <div class="card">
            <div class="card-content">
              <span class="card-title black-text">Upload</span>
              <div class="row">
              <form method="post" class="col s12" enctype="multipart/form-data">
                {% csrf_token %}
                {{ chargerImageForm.non_field_errors }}
                
                <div class="row ">
                    {{ chargerImageForm.photo.errors }}
                    <div class="file-field input-field col s12">
                    <input class="file-path validate" type="text"/>
                        <div class="btn">
                            <span>Photo</span>
                            <input name="photo" type="file" accept="image/*"/>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    {{ chargerImageForm.description.errors }}
                    <div class="input-field col s12">
                    <textarea name="description" id="description" class="materialize-textarea" length="300"></textarea>
                    <label for="description">Description</label>
                    </div>
                </div>
                <button type="submit" value="Submit" class="waves-effect waves-light btn">Charger</button>
            </form>
            </div>
            </div>
            <div class="card-action">
              <a href="{% url 'homework:bureau' %}">Annuler</a>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
{% endblock %}

uploadsapp/homework/templates/etudiant/classeEdition.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    classe {{ classe }}
{% endblock %}

{% block logo %}
    classe {{ classe }}
{% endblock %}

{% block body %}
    <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title black-text">{{ classe }} de {{ classe.professeur }}</span>
                            <p>Vos camarades</p>
                            <ul class="collection">
                                {% for etudiant in classeEtudiants %}
                                    <li class="collection-item">{{ etudiant.user.username }}</li>
                                {% endfor %}
                            </ul>
                        {% if erreur %}
                            <p>Le nom ne correspond pas.</p>
                        {% endif %}
                        <div class="row">
                            <form method="post" class="col s12">
                                {% csrf_token %}
                                {{ quitterClasseForm.non_field_errors }}
                                
                                <div class="row">
                                    {{ quitterClasseForm.nomClasse.errors }}
                                    <div class="input-field col s12">
                                    <label for="{{ quitterClasseForm.nomClasse.id_for_label }}">Saisir le nom de la classe pour quitter</label>
                                    {{ quitterClasseForm.nomClasse }}
                                    </div>
                                </div>
                                
                                <button type="submit" value="Submit" name="quitterClasse" class="waves-effect waves-light btn">Quitter</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

uploadsapp/homework/templates/etudiant/classeIndex.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    Vos classes
{% endblock %}

{% block logo %}
    Vos classes
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col s12">
            {% for classe in classes %}
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title  black-text">{{ classe }}</span>
                            <p>Par {{ classe.professeur }}</div>
                            <div class="card-action">
                            <a href="{% url 'homework:classeEdition' classe.nom %}">Détails</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

uploadsapp/homework/templates/etudiant/devoirEditionPropre.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    {{ devoir.titre }}
{% endblock %}

{% block body %}
    <h1>{{ devoir.titre }}</h1>
    <h2>Proposé par {{ devoir.professeur }}</h2>
    <p>{{ devoir.consigne }}</p>
    <p><img src="{{ devoir.consigneImg.url }}"></p>
    <p>A rendre avant le {{ devoir.dateReddition }}: <a href="{% url 'homework:chargerImage' devoir.titre %}">Charger une image</p>

{% endblock %}

uploadsapp/homework/templates/etudiant/devoirIndex.html
{% extends "baseEtudiant.html" %}
{% load staticfiles %}

{% block titre %}
    Vos devoirs
{% endblock %}

{% block logo %}
    Vos devoirs
{% endblock %}

{% block scripts %}
    <script src="{% static 'tabs.js' %}"></script>
    <script src="{% static 'collapsible.js' %}"></script>
    <script src="{% static 'media.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#aRendre">A rendre</a></li>
        <li class="tab col s3"><a href="#rendu">Rendu</a></li>
      </ul>
    </div>
    <div id="aRendre" class="col s12">
        <ul class="collapsible popout" data-collapsible="accordion">
        {% for devoir in pasFait %}
        <li class="col s12">
            <div class="collapsible-header"><i class=""></i>{{ devoir.titre }} - {{ devoir.dateReddition }}</div>
            <div class="collapsible-body">
                <p>Consigne: {{ devoir.consigne }}</p>
                <img class="responsive-img" src="{{ devoir.consigneImg.url }}">
                <div class="row">
                <a href="{% url 'homework:chargerImage' devoir.titre %}" class="waves-effect waves-light btn">Résoudre !</a>
                </div>
            </div>
        </li>
        {% endfor %}
        </ul>
    </div>
    <div id="rendu" class="col s12">
        <ul class="collapsible popout" data-collapsible="accordion">
        {% for devoir in dejaFait %}
        <li class="col s12">
            <div class="collapsible-header"><i class=""></i>{{ devoir.titre }} - {{ devoir.dateReddition }}</div>
            <div class="collapsible-body">
                <p>Consigne: {{ devoir.consigne }}</p>
                <img class="responsive-img" src="{{ devoir.consigneImg.url }}">
            </div>
            <div class="collapsible-body">
                <p>Réponse: {{ devoir.reponse }}</p>
                <img class="responsive-img" src="{{ devoir.reponseImg.url }}">
            </div>
        </li>
        {% endfor %}
        </ul>
    </div>
  </div>
{% endblock %}

uploadsapp/homework/templates/etudiant/imageEdition.html
{% extends "baseEtudiant.html" %}
{% load staticfiles %}

{% block titre %}
    Image {{ image.devoir }}
{% endblock %}

{% block logo %}
    Image {{ image.devoir }}
{% endblock %}

{% block scripts %}
<script src="{% static 'media.js' %}"></script>
{% endblock %}

{% block body %}
    {% if imageAucune %}
    <p>Vous n'avez proposé aucune réponse pour ce devoir.</p>
    {% else %}
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title black-text">{{ image.devoir }} - le {{ image.date }}</span>
                    <p>{{ image.description }}</p>
                </div>
            </div>
            
            <img class="materialboxed responsive-img" src="{{ image.photo.url }}">
        </div>
    </div>
    {% endif %}
    
{% endblock %}

uploadsapp/homework/templates/etudiant/imageIndex.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    Vos images
{% endblock %}

{% block logo %}
    Vos images
{% endblock %}

{% block body %}
    {% if imageAucune %}
    <p>Vous n'avez aucune image</p>
    {% else %}
    {% for image in images %}
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="{{ image.photo.url }}">
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{ image.devoir }}, le {{ image.date }}<i class="mdi-navigation-more-vert right"></i></span>
                    <p><a href="{% url 'homework:imageEditionEtudiant' image.devoir %}">Détails</a></p>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{ image.devoir }}, le {{ image.date }}<i class="mdi-navigation-close right"></i></span>
                    <p>{{ image.description }}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
{% endblock %}

uploadsapp/homework/templates/etudiant/nonAutorise.html
{% extends "baseEtudiant.html" %}

{% block titre %}
    nonAutorise
{% endblock %}

{% block body %}
    <h1>nonAutorise</h1>
{% endblock %}