uploadsapp/homework/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static

from homework import views

urlpatterns = patterns('',

 url(r'^$', views.accueil, name='accueil'),
 url(r'^inscription/', views.inscription, name='inscription'),
 url(r'^connexion/', views.connexion, name='connexion'),
 url(r'^deconnexion/', views.deconnexion, name='deconnexion'),
 url(r'^bureau/', views.bureau, name='bureau'),
 url(r'^classes/', views.classeIndex, name='classeIndex'),
 url(r'^classe/(?P<classeNom>\w+)/', views.classeEdition, name='classeEdition'),
 url(r'^devoirs/', views.devoirIndex, name='devoirIndex'),
 url(r'^devoir/(?P<devoirTitre>\w+)/', views.devoirEdition, name='devoirEdition'),
 url(r'^chargerimage/(?P<devoirTitre>\w+)/', views.chargerImage, name='chargerImage'),
 url(r'^mesImages/', views.imageIndexEtudiant, name='imageIndexEtudiant'),
 url(r'^monimage/(?P<devoirTitre>\w+)/', views.imageEditionEtudiant, name='imageEditionEtudiant'),
 url(r'^images/(?P<devoirTitre>\w+)/', views.imageIndexProfesseur, name='imageIndexProfesseur'),
 url(r'^image/(?P<imageId>\w+)/', views.imageEditionProfesseur, name='imageEditionProfesseur')
 
)

uploadsapp/uploadsapp/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^homework/', include('homework.urls', namespace="homework")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploadsapp/homework/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Etudiant(models.Model):
    user = models.OneToOneField(User)
    classe = models.ManyToManyField('Classe')
    
    def __str__(self):
        return "Etudiant {}".format(self.user.username)

class Professeur(models.Model):
    user = models.OneToOneField(User) 
    
    def __str__(self):
        return "Professeur {}".format(self.user.username)
        
class Classe(models.Model):
    nom = models.CharField(max_length=50)
    branche = models.CharField(max_length=50)
    professeur = models.ForeignKey("Professeur")
    
    def __str__(self):
        return "{}: {}".format(self.branche, self.nom)
        
class Image(models.Model):
    etudiant = models.ForeignKey("Etudiant")
    photo = models.ImageField(upload_to="etudiants/images")
    devoir = models.ForeignKey("Devoir")
    
    description = models.CharField(max_length=300, null=True)
    
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return "{}: {}".format(self.devoir, self.etudiant)
        
class Devoir(models.Model):
    professeur = models.ForeignKey("Professeur")
    classe = models.ManyToManyField("Classe")
    
    titre = models.CharField(max_length=50)
    consigne = models.CharField(max_length=300)
    consigneImg = models.ImageField(upload_to="professeur/consignes", null=True)
    reponse = models.CharField(max_length=300, null=True)
    reponseImg = models.ImageField(upload_to="professeur/corriges", null=True)
    
    dateCreation = models.DateField(auto_now_add=True)
    dateReddition = models.DateField()
    
    def __str__(self):
        return self.titre

uploadsapp/homework/forms.py
from django import forms
from django.forms.extras.widgets import *

from homework.models import Classe, Etudiant

class InscriptionForm(forms.Form):
    prenom = forms.CharField(label="Prénom", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    nom = forms.CharField(label="Nom", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    courriel = forms.CharField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'validate', 'type': 'email'}))
    modeleCompte = forms.ChoiceField(label='Type de compte', choices=(
        ("professeur", "Professeur"),
        ("etudiant", "Étudiant"),
        ))
    pseudo = forms.CharField(label="Pseudo", max_length=30, widget=forms.TextInput(attrs={'class': 'validate', 'type': 'text'}))
    motDePasse = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class': 'validate', 'type': 'password'}))

class ConnexionForm(forms.Form):
    pseudo = forms.CharField(label="Pseudo", max_length=30, widget=forms.TextInput())
    motDePasse = forms.CharField(label="Mot de passe", widget=forms.PasswordInput())
    
class CreerClasseForm(forms.Form):
    nom = forms.CharField(label="Nom", max_length=50, widget=forms.TextInput())
    branche = forms.ChoiceField(label='Branche', choices=(
        ("", "Choisissez votre Branche"),
        ("Allemand", "Allemand"),
        ("Anglais", "Anglais"),
        ("Arts Visuels", "Arts Visuels"),
        ("Biologie", "Biologie"),
        ("Chimie", "Chimie"),
        ("Français", "Français"),
        ("Histoire", "Histoire"),
        ("Maths", "Maths"),
        ("Musique", "Musique"),
        ("Philosophie", "Philosophie"),
        ("Physique", "Physique"),
        ("Sport", "Sport"),
        ))
    
class EtudiantAjoutForm(forms.Form):
    etudiants = forms.ModelMultipleChoiceField(label="Etudiants à ajouter", queryset=Etudiant.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())

class EtudiantSupprForm(forms.Form):
    etudiants = forms.ModelMultipleChoiceField(label="Etudiants à supprimer", queryset=Etudiant.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())

class QuitterClasseForm(forms.Form):
    nomClasse = forms.CharField(label="Saisir le nom de la classe pour quitter", max_length=50, widget=forms.TextInput())
    
class CreerDevoirForm(forms.Form):
    titre = forms.CharField(label="Titre", max_length=50, widget=forms.TextInput())
    consigne = forms.CharField(label="Consigne", max_length=300, widget=forms.Textarea())
    consigneImg = forms.ImageField(label="Consigne en image", widget=forms.FileInput(attrs={'accept': 'image/*'}))
    reponse = forms.CharField(label="Réponse",  max_length=300, widget=forms.Textarea())
    reponseImg = forms.ImageField(label="Réponse en image", widget=forms.FileInput(attrs={'accept': 'image/*'}))
    dateReddition = forms.DateField(label="Date de reddition", widget=forms.DateInput())
    classe = forms.ModelMultipleChoiceField(label="Classes", queryset=Classe.objects.all(), to_field_name="id", widget=forms.CheckboxSelectMultiple())
    
class DevoirConsForm(forms.Form):
    consigne = forms.CharField(label="Consigne", max_length=300, widget=forms.Textarea())
    
class DevoirConsImgForm(forms.Form):
    consigneImg = forms.ImageField(label="Consigne en image", widget=forms.FileInput())

class DevoirRepForm(forms.Form):
    reponse = forms.CharField(label="Réponse", max_length=300, widget=forms.Textarea())

class DevoirRepImgForm(forms.Form):
    reponseImg = forms.ImageField(label="Réponse en image", widget=forms.FileInput())

class DevoirDateForm(forms.Form):
    dateReddition = forms.DateField(label="Date de reddition", widget=forms.DateInput())

class ChargerImageForm(forms.Form):
    photo = forms.ImageField(label="Photo")
    description = forms.CharField(label="Description", required=False, max_length=300, widget=forms.Textarea(attrs={'class': 'validate', 'type': 'text'}))

uploadsapp/homework/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group

from homework.auth_utils import *
from homework.models import *
from homework.forms import *

def accueil(request):
    return render(request, "homework/accueil.html")
    
def inscription(request):
    if request.user.is_authenticated():
        return redirect("homework:bureau")
    else:
        if request.method == "POST":
            inscriptionForm = InscriptionForm(request.POST, request.FILES)
            
            if inscriptionForm.is_valid():
                username = inscriptionForm.cleaned_data["pseudo"]
                password = inscriptionForm.cleaned_data["motDePasse"]
                first_name = inscriptionForm.cleaned_data["prenom"]
                last_name = inscriptionForm.cleaned_data["nom"]
                eMail = inscriptionForm.cleaned_data["courriel"]
                
                try:
                    User.objects.get(username=username)
                
                except User.DoesNotExist:
                    modeleCompte = None
                    
                    if inscriptionForm.cleaned_data["modeleCompte"] == "etudiant":
                        modeleCompte = Etudiant()
                        group_name = "étudiants"
                        
                    elif inscriptionForm.cleaned_data["modeleCompte"] == "professeur":
                        modeleCompte = Professeur()
                        group_name = "professeurs"
                        
                    user = User.objects.create_user(username, eMail, password)
                    user.first_name = first_name
                    user.last_name = last_name
                    
                    try:
                        groupe = Group.objects.get(name=group_name)
                    
                    except:
                        groupe = Group.objects.create(name=group_name)
                    
                    user.groups.add(groupe)
                    user.save()
                        
                    compte = modeleCompte
                    compte.user = user
                    compte.save()
                    
                    return redirect("homework:connexion")
    
        else:
            inscriptionForm = InscriptionForm()
            
        return render(request, "homework/inscription.html", locals())

def connexion(request):
    if request.user.is_authenticated():
        return redirect("homework:bureau")
    else:    
        erreur = False
        
        if request.method == "POST":
            connexionForm = ConnexionForm(request.POST, request.FILES)
            
            if connexionForm.is_valid():
                username = connexionForm.cleaned_data["pseudo"]
                password = connexionForm.cleaned_data["motDePasse"]
                user = authenticate(username=username, password=password)
                
                if user:
                    login(request, user)
                    
                    return redirect("homework:bureau")
                else:
                    erreur = True
        else:
            connexionForm = ConnexionForm()
            
        return render(request, "homework/connexion.html", locals())
        #return render(request, "material/connexion.html", locals())
        
def deconnexion(request):
    logout(request)
    
    return redirect("homework:accueil")
    
def bureau(request):
    if estEtudiant(request.user):
        etudiant = Etudiant.objects.get(user=request.user)
        classes = etudiant.classe.all()
        images = Image.objects.filter(etudiant=etudiant)
        
        devoirs = Devoir.objects.all().filter(classe=classes).distinct().order_by("-dateReddition")
        
        dejaFait = []
        devoirsAFaire = []
        
        for devoir in devoirs:
            for image in images:
                if image.devoir == devoir:
                    dejaFait.append(devoir)
        
        for devoir in devoirs:
            if devoir not in dejaFait:
                devoirsAFaire.append(devoir)
                
        return render(request, "etudiant/bureau.html", locals())
    
    elif estProfesseur(request.user):
        professeur = Professeur.objects.get(user=request.user)
        classes = Classe.objects.filter(professeur=professeur)
        eleves = []
        
        for classe in classes:
            elevesAAjouter = Etudiant.objects.filter(classe=classe)
            for eleveAAjouter in elevesAAjouter:
                eleves.append(eleveAAjouter)
        
        images = Image.objects.all().order_by("-date")
        
        imagesAMontrer = []
        
        while len(imagesAMontrer) < 5:
            for image in images:
                if image.etudiant in eleves and image not in imagesAMontrer:
                    imagesAMontrer.append(image)
            if len(images) == len(imagesAMontrer):
                break
        if len(imagesAMontrer) == 0:
            imageAucune = True
        else:
            imageAucune = False
        return render(request, "professeur/bureau.html", locals())
    
    else:
        return redirect("homework:connexion")

def classeIndex(request):
    if estProfesseur(request.user):
        erreur = False
        professeur = Professeur.objects.get(user=request.user)
        classes = Classe.objects.filter(professeur=professeur)
        
        if request.method == "POST":
            creerClasseForm = CreerClasseForm(request.POST, request.FILES)
            if creerClasseForm.is_valid():
                classeNom = creerClasseForm.cleaned_data["nom"]
                try:
                    classe = Classe.objects.get(nom=classeNom)
                    erreur = True
                except:
                    classe = Classe()
                    classe.nom = classeNom
                    classe.branche = creerClasseForm.cleaned_data["branche"]
                    classe.professeur = professeur
                    classe.save()
                    creerClasseForm = CreerClasseForm()
        else:
            creerClasseForm = CreerClasseForm()
        
        branches = [("Allemand"),
                    ("Anglais"),
                    ("Arts Visuels"),
                    ("Biologie"),
                    ("Chimie"),
                    ("Français"),
                    ("Histoire"),
                    ("Maths"),
                    ("Musique"),
                    ("Philosophie"),
                    ("Physique"),
                    ("Sport")]
                    
        return render(request, "professeur/classeIndex.html", locals())
    
    elif estEtudiant(request.user):
        etudiant = Etudiant.objects.get(user=request.user)
        classes = etudiant.classe.all()
        
        return render(request, "etudiant/classeIndex.html", locals())
        
    else:
        return redirect("homework:connexion")

def classeEdition(request, classeNom):
    if estProfesseur(request.user) or estEtudiant(request.user):
        classe = Classe.objects.get(nom=classeNom)
        classeEtudiants = Etudiant.objects.filter(classe=classe)
        classeProfesseur = classe.professeur
        etudiantsTous = Etudiant.objects.exclude(classe=classe)
        
        if estProfesseur(request.user):
            professeurConnecte = Professeur.objects.get(user=request.user)
            if professeurConnecte == classeProfesseur:
                if request.method == "POST":
                    if 'etudiantSuppr' in request.POST:
                        etudiantSupprForm = EtudiantSupprForm(request.POST, request.FILES)              
                        if etudiantSupprForm.is_valid():                                                
                            for etudiant in etudiantSupprForm.cleaned_data["etudiants"]:                
                                etudiant.classe.remove(classe)                             
                                etudiant.save()
                                
                                etudiantSupprForm = EtudiantSupprForm()
                                etudiantAjoutForm = EtudiantAjoutForm()
                                etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                                etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
        
                    elif 'etudiantAjout' in request.POST:
                        etudiantAjoutForm = EtudiantAjoutForm(request.POST, request.FILES)
                        if etudiantAjoutForm.is_valid():
                            for etudiant in etudiantAjoutForm.cleaned_data["etudiants"]:
                                etudiant.classe.add(classe)
                                etudiant.save()
                                
                                etudiantSupprForm = EtudiantSupprForm()
                                etudiantAjoutForm = EtudiantAjoutForm()
                                etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                                etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
                else:
                    etudiantSupprForm = EtudiantSupprForm()
                    etudiantAjoutForm = EtudiantAjoutForm()
                    etudiantSupprForm.fields['etudiants'].queryset = Etudiant.objects.filter(classe=classe)
                    etudiantAjoutForm.fields['etudiants'].queryset = Etudiant.objects.exclude(classe=classe)
                
                return render(request, "professeur/classeEditionPropre.html", locals())
            else:
                return render(request, "professeur/classeEditionAutre.html", locals())
        
        elif estEtudiant(request.user):

uploadsapp/homework/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        
        <!--Import materialize.css-->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <meta charset="utf-8">
        <meta name="theme-color" content="#ee6e73">
        <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" />
        <title>{% block titre %}Accueil{% endblock %}</title>
    </head>
    <body>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
        {% block scripts %}{% endblock %}
        <header>
            <div class="navbar-fixed">
                <nav>
                    <a href="#" class="brand-logo">{% block logo %}Accueil{% endblock %}</a>
                    <ul class="right hide-on-med-and-down">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'homework:deconnexion'  %}">Se déconnecter</a></li>
                        {% else %}
                        <li><a href="{% url 'homework:connexion'  %}">Se connecter</a></li>
                        <li><a href="{% url 'homework:inscription'  %}">S'inscrire</a></li>
                        {% endif %}
                    </ul>
                    <ul id="slide-out" class="side-nav">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'homework:deconnexion'  %}">Se déconnecter</a></li>
                        {% else %}
                        <li><a href="{% url 'homework:connexion'  %}">Se connecter</a></li>
                        <li><a href="{% url 'homework:inscription'  %}">S'inscrire</a></li>
                        {% endif %}
                    </ul>
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
                </nav>
            </div>
        </header>
        <main>
        {% block body %}
            <h1>Hello, world!</h1>
        {% endblock %}
        </main>
        <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">© 2015 Copyright Daniel</div>
          </div>
        </footer>
        <script src="{% static 'navbar.js' %}"></script>
    </body>
</html>

uploadsapp/homework/templates/baseAncien.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block titre %}Base{% endblock %}</title>
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    
    {% if user.is_authenticated %}
      <p>{{ user.username }}</p>
      <a href="{% url 'homework:deconnexion'  %}">Se deconnecter</a>
    {% else %}
      <a href="{% url 'homework:connexion'  %}">Se Connecter</a>
      <a href="{% url 'homework:inscription'  %}">S'inscrire</a>
    {% endif %}
    
    {% block body %}
      <h1>Hello, world!</h1>
    {% endblock %}
  </body>
</html>

uploadsapp/homework/templates/baseEtudiant.html
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        
        <!--Import materialize.css-->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <meta charset="utf-8">
        <meta name="theme-color" content="#ee6e73">
        <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" />
        <title>{% block titre %}Accueil{% endblock %}</title>
    </head>
    <body>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
        {% block scripts %}{% endblock %}
        <header>
            <div class="navbar-fixed">
                <nav>
                    <a href="#" class="brand-logo">{% block logo %}Elève: {{ user.username }}{% endblock %}</a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="{% url 'homework:bureau'  %}">Mon bureau</a></li>
                        <li><a href="{% url 'homework:imageIndexEtudiant'  %}">Mes images</a></li>
                        <li><a href="{% url 'homework:classeIndex'  %}">Mes classes</a></li>
                        <li><a href="{% url 'homework:devoirIndex'  %}">Mes devoirs</a></li>
                        <li><a href="{% url 'homework:deconnexion'  %}">Me deconnecter</a></li>
                    </ul>
                    <ul id="slide-out" class="side-nav">
                        <li><a href="{% url 'homework:bureau'  %}">Mon bureau</a></li>
                        <li><a href="{% url 'homework:imageIndexEtudiant'  %}">Mes images</a></li>
                        <li><a href="{% url 'homework:classeIndex'  %}">Mes classes</a></li>
                        <li><a href="{% url 'homework:devoirIndex'  %}">Mes devoirs</a></li>
                        <li><a href="{% url 'homework:deconnexion'  %}">Me déconnecter</a></li>
                    </ul>
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
                </nav>
            </div>
        </header>
        <main class=" grey lighten-5">
        {% block body %}
            <h1>Hello, world!</h1>
        {% endblock %}
        </main>
        <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">© 2015 Copyright Daniel</div>
          </div>
        </footer>
        <script src="{% static 'navbar.js' %}"></script>
    </body>
</html>

uploadsapp/homework/templates/baseProfesseur.html
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        
        <!--Import materialize.css-->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <meta charset="utf-8">
        <meta name="theme-color" content="#ee6e73">
        <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" />
        <title>{% block titre %}Accueil{% endblock %}</title>
    </head>
    <body>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
        {% block scripts %}{% endblock %}
        <header>
            <div class="navbar-fixed">
                <nav>
                    <a href="#" class="brand-logo">{% block logo %}Prof: {{ user.first_name }}{% endblock %}</a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="{% url 'homework:bureau'  %}">Mon bureau</a></li>
                        <li><a href="{% url 'homework:classeIndex'  %}">Mes classes</a></li>
                        <li><a href="{% url 'homework:devoirIndex'  %}">Mes devoirs</a></li>
                        <li><a href="{% url 'homework:deconnexion'  %}">Me deconnecter</a></li>
                    </ul>
                    <ul id="slide-out" class="side-nav">
                        <li><a href="{% url 'homework:bureau'  %}">Mon bureau</a></li>
                        <li><a href="{% url 'homework:classeIndex'  %}">Mes classes</a></li>
                        <li><a href="{% url 'homework:devoirIndex'  %}">Mes devoirs</a></li>
                        <li><a href="{% url 'homework:deconnexion'  %}">Me déconnecter</a></li>
                    </ul>
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
                </nav>
            </div>
        </header>
        <main class=" grey lighten-5">
        {% block body %}
            <h1>Hello, world!</h1>
        {% endblock %}
        </main>
        <footer class="page-footer">
          <div class="footer-copyright">
            <div class="container">© 2015 Copyright Daniel</div>
          </div>
        </footer>
        <script src="{% static 'navbar.js' %}"></script>
    </body>
</html>